spring:
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/tokyo_life_project?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 8529351399-hgik9nvcu2o24vbdqr6av0caahdtgeab.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          facebook:
            clientId: 206876358642112
            clientSecret: 7a8d8685832d4212d10007668b6de439
            scope:
              - email
              - public_profile